"""data/processed/features.parquet -> Postgres `features` table.

Feast's Postgres offline store reads from SQL, not Parquet directly — this
is the source table its PostgreSQLSource points to (task 5). Unlike
feature_metadata.csv (hand-authored, upserted by name), features.parquet is
fully regenerated by build_features.py each time, so this loader does a
full replace (TRUNCATE + insert) rather than an upsert.
"""

from pathlib import Path

import pandas as pd
from dotenv import load_dotenv
from psycopg2.extras import execute_values

from db import get_connection

REPO_ROOT = Path(__file__).resolve().parents[2]
FEATURES_PATH = REPO_ROOT / "data" / "processed" / "features.parquet"

COLUMNS = [
    "id", "created_on", "district", "surface", "property_type",
    "operation_type", "district_avg_price_per_m2", "price_usd",
]


def load_parquet(path: Path = FEATURES_PATH) -> pd.DataFrame:
    df = pd.read_parquet(path)
    df["created_on"] = pd.to_datetime(df["created_on"])
    return df


def replace_features(conn, df: pd.DataFrame) -> None:
    rows = list(df[COLUMNS].itertuples(index=False, name=None))
    with conn.cursor() as cur:
        cur.execute("TRUNCATE TABLE features")
        execute_values(
            cur, f"INSERT INTO features ({', '.join(COLUMNS)}) VALUES %s", rows
        )
    conn.commit()


def main() -> None:
    load_dotenv(REPO_ROOT / ".env")
    df = load_parquet()
    conn = get_connection()
    try:
        replace_features(conn, df)
    finally:
        conn.close()
    print(f"Replaced features table with {len(df)} rows from {FEATURES_PATH.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
